los errores los estamos manejando en el cuerpo de la promesa

la funcion qeu usa el await debe se asincrona

el async awayt es opcionala poner .then()

el objeto error  tiene una parte llamada message

si el array fuera vacio se mostraria el mensaje definido en reject

en el ejemplo estamos simulando una promesa con settimeout pues si demora un tiempo y no se controla esa promesa bien devolvera undefined ya que a la funcion le llega al pincho esperar 